jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: false
        directories:
            any-name:
                namespace_prefix: "App\\Entity"
                path: "%kernel.root_dir%/../config/serializer"
