mysql:
    image: mariadb
    restart: always
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: logika
        MYSQL_USER: logika
        MYSQL_PASSWORD: log
        TERM: xterm
